#!/bin/sh -e

stage=p # prepare only by default
flags=--verbose # default flag for 'patch' et al.
scm=patch # default SCM; use '-S git' et al.
verbose= # default verbosity; switch with --verbose and --quiet
builder=debbuild # override with '-r rpmbuild' or append path

while getopts pcilabsS:vqr: opt
do
	case $opt in
		[pcil]) # prepare, compile, install, list
			stage=$opt
			;;
		[abs]) # build packages (all, binary, source)
		       	stage=$opt
		       	flags=--silent
			;;
		S) # choose SCM
			scm=$OPTARG
			;;
		[q]) # dump verbosity
			verbose=--quiet
			;;
		[v]) # bump verbosity
			verbose=--verbose
			;;
		r) # use alternative package builder
			builder=$OPTARG
			;;
		?)
			exit 1
			;;
	esac
done

for project in cwebbin mmix sgb tetex-anschrift lucida advent xstar debbuild
do
	printf "\n\nbuilding %s\n\n" "$project"
	git checkout $project-master
	case $project in
		"tetex-anschrift") project=anschrift ;;
		"debbuild") verbose="$verbose --without signature" ;;
	esac
	$builder --define="__scm $scm" --define="_default_patch_flags $flags" \
		-b$stage SPECS/$project.spec $verbose
done
