#!/bin/sh -e

# prepare only
stage=p
flags=--verbose
scm=patch
verbose=-v

while getopts pcilabsS:vq opt
do
	case $opt in
		[pcil]) # prepare, compile, install, list
			stage=$opt
			;;
		[abs]) # build packages (all, binary, source)
		       	stage=$opt
		       	flags=--silent
			;;
		S) # choose SCM
			scm=$OPTARG
			;;
		v) # bump verbosity
			verbose=-vv
			;;
		q) # dump verbosity
			verbose=
			;;
		?)
			exit 1
			;;
	esac
done

for project in tetex-anschrift cwebbin lucida mmix sgb advent xstar debbuild
do
	printf "\n\nbuilding %s\n\n" "$project"
	git checkout $project-master
	if [ "$project" = "tetex-anschrift" ]
	then
		project=anschrift
	fi
	debbuild --define="__scm $scm" --define="_default_patch_flags $flags" \
		-b$stage SPECS/$project.spec $verbose
done
