#!/bin/sh -e

# prepare only
stage=p
flags=--verbose
scm=patch

while getopts pcilabsS: opt
do
	case $opt in
		[pcil]) # prepare, compile, install, list
			stage=$opt
			;;
		[abs]) # build packages (all, binary, source)
		       	stage=$opt
		       	flags=--silent
			;;
		S)	# choose SCM
			scm=$OPTARG
			;;
		?)
			exit 1
			;;
	esac
done

printf "\n\nbuilding cwebbin with makemake patch\n\n"
debbuild -b$stage SPECS/cwebbin.spec

for extension in tgz tar tar.bz2 tar.gz tar.xz zip
do
	printf "\n\nbuilding from advent-1.0.%s\n\n" "$extension"
	debbuild -D "_default_patch_flags $flags" \
		-t$stage advent-1.0.$extension
done

printf "\n\nbuilding advent with patches\n\n"
git checkout SPECS/advent.spec
debbuild --define="__scm $scm" --define="_default_patch_flags $flags" \
	-b$stage SPECS/advent.spec

printf "\n\nCheck '%%_CamelCase_Macros'\n\n"
debbuild -bp SPECS/Camel.spec
rpmbuild -bp SPECS/Camel.spec

printf "\n\nCheck other specials\n\n"
debbuild -bp SPECS/dummy.spec

printf "\n\nbuilding hello project\n\n"
debbuild --define="_default_patch_flags $flags" \
	-b$stage SPECS/hello.spec

printf "\n\nbuilding Pod::Simple project\n\n"
debbuild --define="_default_patch_flags $flags" \
	-b$stage SPECS/perl-Pod-Simple.spec
